### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by frolic** [latticexyz/dac-dashboard#7]
- [x] open question around how to make commitments actionable (challenge, resolve, expire)
- [x] make filter form responsive to input and potentially auto reload data while typing (should prob debounce this though)
  - this is tricky right now with the client/server component boundary, because once we opt in one thing to hooks (e.g. form state on client), we can't use things like async functions to refetch the commitments query and have to thread through everything as a hook
  - I took an initial pass at this just using a form with GET (i.e. query params) and think we should continue to use query params for this (so we get deep linking) but should figure out how to refetch commitments as the query changes
- [x] input commitment page to show all challenge statuses
- [x] dialog when clicking the "challenge" etc. buttons with terminal commands
- [ ] figure out how we want to handle new incoming data e.g. twitter "there are x new tweets, click to load" approach vs just auto inserting them (but should prob not do this if you're hovering the content area to avoid interruptions of click targets)
- [ ] pagination? imo should be the last thing we do once we get filtering in place and we discover it's not enough
- [x] interaction states (button hover/click/focus, input hover/click/focus)
- [ ] page transitions?
- [ ] mobile/responsiveness?
- [ ] fonts
- [ ] make "connect wallet" button look nice (theme, position on page, etc.), blocked on design
- [ ] show a mobile friendly full-screen warning/note that this site isn't mobile-first yet
- [ ] style toasts to match?
- [x] fix issue where modal -> connect wallet -> target is not rainbowkit UI and clicking anywhere dismisses modal
- [x] update to latest contracts
  - [x] remove expiring state (only expired)
- [x] remove to/from filter
- [x] add query support for other filters
- [ ] extra status entry in commitment page between submitted/challenged -> expiring/expired?
- [ ] make modal a url route so it's linkable
- [x] refresh commitment/challenge state based on contracts
- [ ] coinbase wallet may not allow adding or switching network (Switch network button does ~nothing)
- [x] use input hash as commitment url param (not tx hash)
- [ ] show input hash (and tx hash?) somewhere on homepage/commitments results for easy copy/paste
- [x] make the truncated addresses/hashes easier to copy/paste
- [x] add hover label to button so transitions look better (without clipping)
- [ ] decide if contract write button should wait for tx to confirm or just tx to mempool
- [x] fix filter on challenged/expired
- [ ] rainbowkit doesn't add holesky when switching network with rainbowkit built-in UI
- [ ] add `getButtonLabel` to go from error state to button label, so we can translate e.g. "insufficient funds"
- [ ] meta tags
- [ ] opengraph images
- [ ] select dropdown text is white on windows
- [ ] show checkmark icon when contract write completes?
- [ ] reload page data + dismiss modal when contract write completes
- [ ] poll for indexer state after write completes
